language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: WAkfkxc2gzFg37V0ZwLXUiJvHr5u5R8l/rRGqDQyllHzj1L8z0Vh0po+iDeFYhHSSFMWX+1fMUULm/FxMz3KpWMCI5gWln5XDNfVTXOnslxGMbR7ujoW+luB/8m4uy01fFJevL8J0KMRxJc7orx50EouCxidV6tJIjvQRDWFSXMaLw/hYk/ysCAB6+5Z9Ip5pbSWDAs0P0gVRI+Fmx4PvCM6Emrk40GvD3wTlBbMKmNEX8S2vlj+kcRCYHiyngzAD8Q2HZcuMtdicfXTyqAn9YMpbnfKHGholKx3ZA8UY5fg0Ued+axWwShJBUG1xopvNAElbUzDRxCe2X5xOMEjxzaPtwjXHBoOmQZn7JmD1LV+e3nl0ykPlYsLDnh5dJvNXB1tMWhSqjNuch2RRiybPFt1+MqIChqHu050chV9HP+9iEYkcwQxgk6v6Af3jSP+Cbb88PK9w1MOJwd98WycHLdVn4ldn2icSCiTny6uRJ+3Ek8Wc931WtENICHbr8aNJGjV15rhxJdX2bwGjOSyU2loFuj8E0AcVEfdstDtv35+nSjDxbl617qBvR32FWouiWpvr391ep26RsocXKRtetoUVFXp4HkigL7m+kXaZ9s6J153Dhazrz+fst/AObDnTzWSH+ueQPVT5nUIYkrVT45hCNLKBKJQlz/JzoSE4tU=
  app: solitary-bird